{
 "title": "RPSDashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Avg. cluster CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. cluster memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"contoso-names-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"contoso-names-backend\", code=\"200\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{app=\"contoso-names-backend\"}[1m])) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}